### ISSUE TITLE
Bug - "N and Stun" damage letter case

### ISSUE THREAD

**Issue by MeGaZlo** [USSX-Hares/hammerhal#8]
**Input:** damage "1 and Stun"
**Actual:** "1 And Stun"
**Expected:** "1 and Stun"

В картах присутствует вариант оружия, наносящего урон+оглушение. В "официальном" варианте "and" пишется с маленькой буквы, однако программа автоматически ставит после пробелов большую.
Возможно стоит убрать автоматический регистр для графы оружия и урона?

**Comment by USSX-Hares** [comment]
Should took some improvements in the core.

**Comment by USSX-Hares** [comment]
@MeGaZlo 
Fixed with 920fcdeb439b0e6dcf9ad29fb03a3e14ec287662 and 0b3e2689d6391f8008d453e24b94bd3199c83814
